### ISSUE TITLE
Add Token Burn api route

### ISSUE THREAD

**Issue by jbuice** [telosnetwork/api-telos-net#122]
## Overview
Artemis would like to track our token burns on their dashboard. 

Burns occur as the `retire` action on contract `eosio.token`

I belive returning a total tokens burned number would suffice. 

Perhaps /v1/supply/burns

**Comment by rozzaswap** [comment]
High priority but can wait until after 1.5 deployment

**Comment by tomtomcrypto** [comment]
@jbuice @rozzaswap What number do we give back ? Do we take care of decimals and give back results suche as 54.544 or do we give back 5454400 with 5 as decimals.

**Comment by jbuice** [comment]
What has typically been our standard for supply? I would suggest we match that.

**Comment by tomtomcrypto** [comment]
`token/supply/:contract/:symbol/burnt`
